### PR TITLE
Updated missing punctuation in the README.md file

### PR DESCRIPTION
**Pull request by sumitkharche**

### CODE REVIEW

**Comment by sumitkharche** [comment]
I have just updated README.md and index.md files. Some of the checks are not passing. Don't know how this is related to documentation changes. @sudermanjr & @lanceops  could you please provide your input on this?

**Comment by sumitkharche** [comment]
@lanceops Thanks for the review.

**Comment by sudermanjr** [comment]
Tests failed due to steps that don't support external PRs.  We need to fix some of that.

**Comment by sumitkharche** [comment]
Thanks @sudermanjr  and @lanceops for the reviews.

**Pull request merged**
